const products = [
  {
    id: 0,
    name: "Honda NSX 1990",
    price: 13.99,
    instock: 7,
    description: "lorem",
    imgSrc: "./img/c1.png",
  },
  {
    id: 1,
    name: "Nissan 300ZX",
    price: 13.99,
    instock: 3,
    description: "lorem",
    imgSrc: "./img/c2.png",
  },
  {
    id: 2,
    name: "VW Golf MK2",
    price: 19.99,
    instock: 2,
    description: "lorem",
    imgSrc: "./img/c3.png",
  },
  {
    id: 3,
    name: "Mazda Miata 2018",
    price: 11.99,
    instock: 12,
    description: "lorem",
    imgSrc: "./img/c4.png",
  },
  {
    id: 4,
    name: "Porsche 911 1990",
    price: 29.99,
    instock: 1,
    description: "lorem",
    imgSrc: "./img/c6.png",
  },
  {
    id: 5,
    name: "Nissan R33",
    price: 19.99,
    instock: 3,
    description: "lorem",
    imgSrc: "./img/c7.png",
  },
];
