const products = [
  {
    id: 0,
    name: "Honda NSX 1990",
    price: 13.99,
    instock: 7,
    description: "A 2 door japanese coupé with a mid mounted engine",
    imgSrc: "./img/c1.png",
  },
  {
    id: 1,
    name: "Nissan 300ZX",
    price: 13.99,
    instock: 3,
    description: "A sports car in the Nissan Z-car family, NSX' rival",
    imgSrc: "./img/c2.png",
  },
  {
    id: 2,
    name: "VW Golf MK2 GTI",
    price: 19.99,
    instock: 2,
    description: "The legendary successor to the Volkswagen Golf Mk1",
    imgSrc: "./img/c3.png",
  },
  {
    id: 3,
    name: "Mazda Miata 2018",
    price: 11.99,
    instock: 12,
    description: "A rear-wheel-drive chassis and a rev-happy engine",
    imgSrc: "./img/c4.png",
  },
  {
    id: 4,
    name: "Porsche 911 1990",
    price: 29.99,
    instock: 1,
    description: "A two-door, high performance rear-engined sports car",
    imgSrc: "./img/c6.png",
  },
  {
    id: 5,
    name: "Nissan R33",
    price: 19.99,
    instock: 3,
    description: "The fourth generation of the skyline family, features AWD",
    imgSrc: "./img/c7.png",
  },
];
